Added redis packaging script

diff --git a/packages/redis/packaging b/packages/redis/packaging
--- a/packages/redis/packaging
+++ b/packages/redis/packaging
@@ -1,11 +1,13 @@
-# abort script on any command that exit with a non zero value
-set -e
-
-tar xfz redis/redis-2.4.13.tar.gz
+tar zxf redis/redis-2.4.13.tar.gz
+ 
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting redis"
+  exit 1
+fi
+ 
 (
   cd redis-2.4.13
-  ./configure --prefix=$BOSH_INSTALL_TARGET
   make
-  make install
+  make PREFIX=$BOSH_INSTALL_TARGET install
 )
 
